### ISSUE TITLE
Changing functions signatures

### ISSUE THREAD

**Issue by hasauino** [hbrs-ai/assignment-03#1]
Are we allowed to change function signatures for the ones defined by you. For example the ``` maze_map_to_tree``` function takes the map as argument, can we add more arguments?

**Comment by PatrickNa** [comment]
@hasauino yes you are allowed to change the signature of the functions. But remember to adjust the doc string accordingly. 

Please use LEA for this type of questions. Issues on GitHub do not reach the rest of the class.
